### DISCUSSION TITLE
An API provider controlling users' ability to bind to its APIExport

### DISCUSSION THREAD

**Discussion by ncdc** [kcp-dev/kcp#2068] [General]
Currently a user must have `bind` permission (via RBAC) to create an APIBinding that references a specific APIExport. The `bind` permission is currently allowed via a ClusterRole that specifically mentions the APIExport by name (wildcards are not supported at this time - see #1939), such as:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:kcp:apiexport:tenancy:bind
rules:
- apiGroups: ["apis.kcp.dev"]
  resources:
  - "apiexports"
  resourceNames:
  - "tenancy.kcp.dev"
  verbs: ["bind"]
```

And here is an example ClusterRoleBinding that allows all authenticated users to bind to this APIExport:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:kcp:authenticated:apiexport:tenancy:bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kcp:apiexport:tenancy:bind
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
```

We have an admission controller that enforces this `bind` verb requirement.

We've recently had some discussions around taking additional information into account when authorizing APIBinding creation. One example scenario is where an API provider may want to allow or reject an APIBinding based on its containing workspace. For example, imagine this setup:

```
root:api-provider
root:users:bob
root:users:alice
```

- bob gets access to bind to APIExports from `root:api-provider`
- alice does not have this permission
- alice gives bob cluster-admin in `root:users:alice`
- the API provider is happy that bob is trying out the APIs, but they don't really want bob to bind to their APIExport anywhere and everywhere he has permission to create APIBindings (e.g. in `root:users:alice`)

Some reasons why this might not be desirable, from the API provider's perspective:
- there is a cost incurred by the API provider when users use their APIs
    - the API provider wants to use ResourceQuota to limit how many instances of their APIs can be created "by a user"
    - "by a user" actually gets translated to "within a workspace subtree" because there is no hard concept of ownership of kube-like APIs
    - the API provider is able to establish quota in `root:users:bob` when bob creates his APIBinding, and they're happy knowing bob can't exceed the quota they set
    - if bob is able to create new APIBindings in other workspaces, especially outside of the `root:users:bob` subtree, he can effectively get around the quota restrictions

Does this resonate with folks? Is this something we should pursue?
