### ISSUE TITLE
Using the downward API on deployment causes issues as it leaks the pcluster information

### ISSUE THREAD

**Issue by jmprusi** [kcp-dev/kcp#1191]
**Describe the bug**

When using the downward API to expose information to Pods, the information will be the one from the PCluster instead of the KCP one, for ex: the namespace. This causes problems when relying on that information to make calls to the k8s API. 

(The downward API can be used in ENV vars or Volumes)

**To Reproduce**
1. Create a deployment that sets a Pod template env var using the downward API:
```          
env:
  - name: NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
```
2. make a k8s call from that POD using the provided env var.

**Expected behavior**
The expected value should be the one from the KCP server.
