### ISSUE TITLE
Downward API references in Deployment volumes leak pcluster information

### ISSUE THREAD

**Issue by jmprusi** [kcp-dev/kcp#1198]
**Describe the bug**

When using the downward API to expose information to Pods, the information will be the one from the PCluster instead of the KCP one, for example and most important the namespace. This causes problems when relying on that information to make calls to the k8s API.

**To Reproduce**

1. Create a deployment that uses a volume to pull information from the downward API:
```          
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "namespace"
            fieldRef:
              fieldPath: metadata.namespace
```
2. make a k8s call from that Pod using the information provided by the volume.

**Expected behavior**

The expected value should be the one from the KCP server.
