### ISSUE TITLE
Setting an owner reference in a CR and then deleting the owner does not delete the owned CR

### ISSUE THREAD

**Issue by pdettori** [kcp-dev/kcp#1326]
**Describe the bug**
I have been testing Crossplane with KCP, and one of the issues I have found is with deletion of Crossplane composite resources.  When I delete a Crossplane Claim or XR, all Crossplane managed resources that are owned by that XR are not deleted. Crossplane sets an owner reference in each managed resource, so that when the owner is deleted all the managed resources are cascade-deleted. 

**To Reproduce**
I tested the following in a "regular" Kubernetes cluster (no Crossplane or controllers for the sample CRs installed)

1. Create and enter a kcp workspace
2. Unzip and apply the attached CRDs 
3.  Create the owner CR first:
```
apiVersion: optimizers.aether.cloud.ibm.com/v1alpha1
kind: ClaimOwner
metadata:
  name: claim-owner-test
spec:
  foo: hello
```
4. Take note of the UID for the owner CR and write it in the owned CR
```
apiVersion: optimizers.aether.cloud.ibm.com/v1alpha1
kind: Claim
metadata:
  name: claim-sample
  ownerReferences:
  - apiVersion: optimizers.aether.cloud.ibm.com/v1alpha1
    controller: true
    kind: ClaimOwner
    name: claim-owner-test
    uid: <enter here the UID from owner >
spec:
  foo: hello
  ```
5. apply the above CR
6. Delete the owner CR, verify that the owned CR does NOT get deleted

7. Repeat steps 3-6 on a regular kube cluster, verify that the owned CR DOES get deleted.

**Expected behavior**
I would expect that deleting the owner CR deletes the owned CR, as in a standard Kubernetes API server

**Additional context**
[crds.zip](https://github.com/kcp-dev/kcp/files/8953967/crds.zip)
