### ISSUE TITLE
Internal error when creating a ClusterRole while authenticated as a ServiceAccount

### ISSUE THREAD

**Issue by robinbobbitt** [kcp-dev/kcp#1340]
**Describe the bug**
I am authenticated to KCP (main branch instance) as a service account that I created and gave a bunch of permissions to, including creating ClusterRoles and working with WorkloadClusters. When I attempt to create a ClusterRole, I am getting a permission error that seems incorrect and the Internal error seen below:
```
% cat clusterroleascontroller.yaml 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fred
rules:
- apiGroups: ["workload.kcp.dev"]
  resources: ["workloadclusters"]
  verbs: ["get", "list", "watch"]
% k apply -f clusterroleascontroller.yaml
Error from server (Forbidden): error when creating "clusterroleascontroller.yaml": clusterroles.rbac.authorization.k8s.io "fred" is forbidden: user "system:serviceaccount:default:singapore" (groups=["system:serviceaccounts" "system:serviceaccounts:default" "system:authenticated"]) is attempting to grant RBAC permissions not currently held:
{APIGroups:["workload.kcp.dev"], Resources:["workloadclusters"], Verbs:["get" "list" "watch"]}; resolution errors: [Internal error occurred: unable to get cluster for list key "/registry/rbac.authorization.k8s.io/clusterrolebindings/": no cluster in the request context]
```

**To Reproduce**
1. Create a new ServiceAccount in your KCP workspace.
2. Create the following ClusterRole and bind it to your ServiceAccount:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceaccount-crudl
rules:
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["create", "get", "watch", "list", "update", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings"]
  verbs: ["create", "get", "watch", "list", "update", "delete"]
- apiGroups: ["workload.kcp.dev"]
  resources: ["workloadclusters"]
  verbs: ["create", "get", "watch", "list", "update", "delete", "patch"]
- apiGroups: ["workload.kcp.dev"]
  resources: ["workloadclusters/status"]
  verbs: ["update", "patch"]
- apiGroups: ["apiresource.kcp.dev"]
  resources: ["apiresourceimports"]
  verbs: ["create", "get", "watch", "list", "update", "delete"]
```
4. Authenticate as the ServiceAccount you created in the steps above
5. Attempt to create a ClusterRole like the example given above.

**Expected behavior**
The ClusterRole is created successfully.
