### ISSUE TITLE
Universal initializer is not cleaned (and probably not even called) when extended by a child CWT

### ISSUE THREAD

**Issue by MatousJobanek** [kcp-dev/kcp#1553]
**Describe the bug**
When a new CWT is created by extending the `universal` one:
```yaml
apiVersion: tenancy.kcp.dev/v1alpha1
kind: ClusterWorkspaceType
metadata:
  name: foo
spec:
  additionalWorkspaceLabels:
    workloads.kcp.dev/schedulable: "true"
  allowedChildren:
    any: true
  allowedParents:
    any: true
  extend:
    with:
      - name: universal
        path: root
```
and when the new CWT is used, then the creation gets stuck on waiting to be ready. After some time it fails with timeout:
```
$ k ws create bar --type foo
Workspace "bar" (type root:org:test:foo) created. Waiting for it to be ready...
Error: timed out waiting for the condition
```

When looking at the Workspace `bar` CR, it still contains the initializer:
```yaml
spec:
  type:
    name: foo
    path: root:org:test
status:
  URL: https://192.168.1.128:6443/clusters/root:org:test:bar
  conditions:
  - lastTransitionTime: "2022-07-18T11:38:22Z"
    message: 'Initializers still exist: [root:universal]'
    reason: InitializerExists
    severity: Info
    status: "False"
    type: WorkspaceInitialized
  initializers:
  - root:universal
  phase: Initializing
```

I tried to get all APIBindings in the workspace, but the list is empty: 
```
$ k get apibinding --server https://192.168.1.128:6443/clusters/root:org:test:bar
No resources found
```

so I assume that the universal initializer is not called at all.

**Expected behavior**
The `universal` initializer does its job and removes the name from the list of initializers
