### ISSUE TITLE
apibinding falls in error after kcp restart

### ISSUE THREAD

**Issue by itdove** [kcp-dev/kcp#1564]
**Describe the bug**
After restarting kcp, the apibinding falls in error
```
  - lastTransitionTime: "2022-07-14T21:45:16Z"
    message: An internal error occurred with the APIExport
    reason: InternalError
    severity: Error
    status: "False"
    type: APIExportValid
```
however the APIEXport is
```
  conditions:
  - lastTransitionTime: "2022-07-14T15:13:34Z"
    status: "True"
    type: IdentityValid
  - lastTransitionTime: "2022-07-14T15:13:34Z"
    status: "True"
    type: VirtualWorkspaceURLsReady
```

**To Reproduce**
1. Launch the kcp start v0.6.0-alpha.0
2. Create my org under root (root:org).
3. Create the apiexport.
4. Create my ws under the org (root:org:ws)
5. Create there the apibinding.
6. Kill kcp
7. Relaumch kcp start
8. Check apibinding status

**Expected behavior**
Apibinding still be ok

**Additional context**
kcp v0.6.0-alpha.0
