### ISSUE TITLE
Document SyncTarget "cells" concept

### ISSUE THREAD

**Issue by markmc** [kcp-dev/kcp#1622]
`SyncTarget.Spec.Cells` was added in #1571

`locations-and-scheduling.md` would be a good place to document this

Pasting the breadcrumbs of design discussion I can find ...

> we might have something called a "network cell" of clusters with joint pod+service networking. By default, a BYO cluster fleet would have single-cluster cells.

> this does not mean that all clusters in a location must have pod IP connectivity. It only means that one scheduled workspace must roam only between clusters that have. I.e. we can build many network connnectivity cells within a location (similarly for storage).

> our goal to support operations in a cell within a location and to guarantee conformance and no disruption

[Meeting conclusion](https://kubernetes.slack.com/archives/C021U8WSAFK/p1658138320873169?thread_ts=1658127849.906039&cid=C021U8WSAFK) describing API variants and cells

[Google doc](https://docs.google.com/document/d/10Tloa3IZ36PV5JJodxKeA3p65ivVqgpwmqqsOwUWewg) 

```
# the cell identities as a set define applicable sync targets for scheduling. A workload on
# a sync target with some set of cell identities cannot move to another sync target with
# different cell identities.
cellIdentity:
- key: network
  value: 234234bnvgh2f43
- key: storage
  valuel: asdfasdf
```

[Slack thread](https://kubernetes.slack.com/archives/C021U8WSAFK/p1658396023636429)

> add cells to the SyncTarget spec ... we will need that for a user experience that does not break BYO users.

> don't think a user can refernece these labels, it's just for the compute service operator

> it is a hint for rescheduling or migration. i.e. if cells is different, the workload cannot not move

> its invisible to users, the only guarantee they get: one workspace cannot span cells in the same location

> workload movement requires (network cell same) && (storage cell same). will (network same && storage diff) indicate anything? maybe depends on workload scheduler. if a workload is stateless, the (network cell same) is sufficient for movement.

```
cells:
  network: "10.43.0/16"
  storage: "fiber-channel-3"
```

> the set of clusters where a workload can move is the intersection of network cell, storage cell, whatever cell.
