### ISSUE TITLE
kubectl get locations --show-labels displays two columns with same name LABELS

### ISSUE THREAD

**Issue by kasturinarra** [kcp-dev/kcp#1625]
**Describe the bug**
When kubectl get locations --show-labels command is run i see that there are two columns with same name LABELS and one of them actually displays the labels that are assigned to location another one is blank, it might be confusing to the user on what the other column is actually for.

**Version**
```
[knarra@knarra ~]$ kubectl version -o yaml
clientVersion:
  buildDate: "2022-07-07T20:21:05Z"
  compiler: gc
  gitCommit: f17f1aa456e00569e88a0e8206c5b360e44055dd
  gitTreeState: clean
  gitVersion: v1.24.1
  goVersion: go1.18.1
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-07-26T15:00:58Z"
  compiler: gc
  gitCommit: 8ad1c4a
  gitTreeState: dirty
  gitVersion: v1.24.3+kcp-v0.0.0-8ad1c4a
  goVersion: go1.17.12
  major: "1"
  minor: "24"
  platform: linux/amd64
```

**To Reproduce**
1. Create a workspace using the command `kubectl ws create qetest1 --enter`
2. Prepare a openshift cluster and add a sync target by running the command `kubectl kcp workload sync <sync-target-name> --syncer-image <kcp-syncer-image> -o - | KUBECONFIG=<pcluster-config> kubectl apply -f -`
3. Run command `kubectl get locations` and you can see that synctarget we added becomes  the location
4. Now add label to the location to be able to schedule a workload to that by running command `kubectl label location default cluster1=ocpcluster
5. Now run the command to check if the label has actually got applied by running the command `kubectl get locations --show-labels`
```
[knarra@knarra ~]$ kubectl get locations --show-labels
NAME      RESOURCE      AVAILABLE   INSTANCES   LABELS   LABELS
default   synctargets   1           1                    cluster1=ocpcluster
```

**Expected behavior**
 Only one LABEL column should be shown otherwise it might be confusing for the user.

**Additional context**
