### ISSUE TITLE
bug: APIs bound through Permission Claims not available when using identityHash

### ISSUE THREAD

**Issue by johnmcollier** [kcp-dev/kcp#1845]
### Describe the bug

When specifying another APIExport's identityHash in a permission claim in an APIExport / APIBinding, the APIBinding will create successfully:

E.g.:
```
apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  name: has-binding
spec:
  reference:
    workspace:
      path: root:has
      exportName: has
  acceptedPermissionClaims:
      - group: ""
        resource: "secrets"
        verbs: ["get", "list", "watch"]
      - group: ""
        resource: "configmaps"
        verbs: ["get", "list", "watch"]
      - identityHash: 5d8e0fa5f9a10dbff668aad2cd63777e061c837e3f0a2f1adda15f7acae9fd53
        group: "appstudio.redhat.com"
        resource: "environments"
      - identityHash: 5d8e0fa5f9a10dbff668aad2cd63777e061c837e3f0a2f1adda15f7acae9fd53
        group: "appstudio.redhat.com"
        resource: "applicationsnapshotenvironmentbindings"
```

with the following status conditions:
```
  conditions:
  - lastTransitionTime: "2022-08-26T18:24:05Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2022-08-26T18:24:05Z"
    status: "True"
    type: APIExportValid
  - lastTransitionTime: "2022-08-26T18:24:05Z"
    status: "True"
    type: BindingUpToDate
  - lastTransitionTime: "2022-08-26T18:24:05Z"
    status: "True"
    type: InitialBindingCompleted
  - lastTransitionTime: "2022-08-26T18:24:05Z"
    status: "True"
    type: PermissionClaimsApplied
  - lastTransitionTime: "2022-08-26T18:24:05Z"
    status: "True"
    type: PermissionClaimsValid
```

But if I run `kubectl get environments` the command fails, saying `error: the server doesn't have a resource type "environments"
`

### Steps To Reproduce

I've created a reporducer here: https://github.com/johnmcollier/kcp-permissionclaims-reproducer

### Expected Behaviour

The APIs specified in the permission claims are available.
