### ISSUE TITLE
bug: Claiming permissions on SAR or SRR fail

### ISSUE THREAD

**Issue by astefanutti** [kcp-dev/kcp#1922]
### Describe the bug

Trying to add permission claims for `authorization.k8s.io/selfsubjectaccessreviews` or `authorization.k8s.io/selfsubjectrulesreviews` fail, with the APIBinding reporting the following `PermissionClaimsApplied` condition:

```yaml
  message: 'Permission claims have not been fully applied: [error getting informer
      for group="authorization.k8s.io", resource="selfsubjectaccessreviews": unable
      to find informer for authorization.k8s.io.selfsubjectaccessreviews, error getting
      informer for group="authorization.k8s.io", resource="selfsubjectrulesreviews":
      unable to find informer for authorization.k8s.io.selfsubjectrulesreviews]'
  reason: InternalError
  severity: Error
  status: "False"
  type: PermissionClaimsApplied
```

### Steps To Reproduce

Create an APIExport with:
```yaml
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
spec:
  permissionClaims:
    - group: "authorization.k8s.io"
      resource: "selfsubjectrulesreviews"
      identityHash: ...
    - group: "authorization.k8s.io"
      resource: "selfsubjectaccessreviews"
      identityHash: ...
```

And an APIBinding with:
```yaml
apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
spec:
  reference:
    workspace:
      path: ...
      exportName: ...
  permissionClaims:
    - group: "authorization.k8s.io"
      resource: "selfsubjectrulesreviews"
      identityHash: ...
      state: "Accepted"
    - group: "authorization.k8s.io"
      resource: "selfsubjectaccessreviews"
      identityHash: ...
      state: "Accepted"
```

### Expected Behaviour

It should be possible to claim permissions on SAR and SRR resources.

### Additional Context

It seems the `permissionclaimlabel` controller lists claimed resources to apply a label. However SAR, nor SRR, resources cannot be listed, as they only support the `create` operation.
