### ISSUE TITLE
bug: failure to provide identity hash in APIExport / APIBinding permission claims fails silently

### ISSUE THREAD

**Issue by hasheddan** [kcp-dev/kcp#2152]
### Describe the bug

I had an `APIExport` that included `permissionClaims` for `deployments/apps`. `Deployments` are not a built-in type, and are only available in a given workspace after setting up a `SyncTarget` to a pcluster (which creates an `APIExport` with name `kubernetes`). 

```
$ k get apiexports kubernetes -o yaml
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  annotations:
    kcp.dev/cluster: root
    workload.kcp.dev/skip-default-object-creation: "true"
  creationTimestamp: "2022-10-07T12:17:03Z"
  generation: 3
  name: kubernetes
  resourceVersion: "506"
  uid: e3af3dac-d89a-48ff-8921-5fd0826a7cd3
spec:
  identity:
    secretRef:
      name: kubernetes
      namespace: kcp-system
  latestResourceSchemas:
  - rev-503.deployments.apps
status:
  conditions:
  - lastTransitionTime: "2022-10-07T12:17:03Z"
    status: "True"
    type: IdentityValid
  - lastTransitionTime: "2022-10-07T12:17:03Z"
    status: "True"
    type: VirtualWorkspaceURLsReady
  identityHash: 5fdf7c7aaf407fd1594566869803f565bb84d22156cef5c445d2ee13ac2cfca6
  virtualWorkspaces:
  - url: https://192.168.1.189:6443/services/apiexport/root/kubernetes
```

The `permissionClaims` in my `APIExport` looked like the following:
```yaml
  permissionClaims:
  - group: ""
    resource: secrets
  - group: ""
    resource: namespaces
  - group: ""
    resource: configmaps
  - group: apps
    # (SHOULD HAVE THIS) identityHash: 5fdf7c7aaf407fd1594566869803f565bb84d22156cef5c445d2ee13ac2cfca6
    resource: deployments
```

Because I did not have the identity hash provided, when I created an `APIBinding` for the export, `Deployments` did not show up in the virtual workspace for the exported types.

```
$ k -s https://192.168.1.189:6443/services/apiexport/root/kxp.crossplane.io/clusters/* api-resources
NAME                           SHORTNAMES   APIVERSION                             NAMESPACED   KIND
configmaps                                  v1                                     true         ConfigMap
namespaces                                  v1                                     false        Namespace
secrets                                     v1                                     true         Secret
```

However, the failure for the permission claim to be applied was not reflected in the export (see in status above) or binding:
```
   conditions:
  - lastTransitionTime: "2022-10-07T12:54:01Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2022-10-07T12:54:01Z"
    status: "True"
    type: APIExportValid
  - lastTransitionTime: "2022-10-07T12:54:01Z"
    status: "True"
    type: BindingUpToDate
  - lastTransitionTime: "2022-10-07T12:54:01Z"
    status: "True"
    type: InitialBindingCompleted
  - lastTransitionTime: "2022-10-07T12:54:01Z"
    status: "True"
    type: PermissionClaimsApplied
  - lastTransitionTime: "2022-10-07T12:54:01Z"
    status: "True"
    type: PermissionClaimsValid
  exportPermissionClaims:
  - resource: secrets
  - resource: namespaces
  - resource: configmaps
  - group: apps
    resource: deployments
```

### Steps To Reproduce

(these are example steps, the same could be accomplished via a `permissionClaim` that doesn't reference an identity hash on any type provided by an `APIExport`)
1. Setup `SyncTarget` with `kubernetes` `APIExport`.
2. Create `APIExport` referencing `deployments/apps`
3. Create `APIBinding` to a workspace that references the `APIExport` and accepts the `permissionClaims`
4. Observe the type not being available in the virtual workspace for the api export

### Expected Behaviour

I would expect that the `APIExport` would either be rejected on creation (via admission) or for failure to be surfaced in conditions. There is a bit of nuance here around different types of errors for export / binding. For example:
- something like admission could be used to say "this isn't a built-in type, so you need _some_ identity hash"
- something like conditions could be used to say "your identity hash is incorrect" (this may already be the case, need to double check)
