### ISSUE TITLE
bug: Double identity decorations on URLs

### ISSUE THREAD

**Issue by mjudeikis** [kcp-dev/kcp#2184]
### Describe the bug

If you are binding resources from 3rd party APIs with identityHash, sometimes you end-up with double decorations on URL. 

In example `APIExport` :
```
apiVersion: apis.kcp.dev/v1alpha1            
kind: APIExport                              
metadata:                                    
  annotations:                               
    kcp.dev/cluster: root:compute:controllers
  creationTimestamp: "2022-10-12T17:16:54Z"
  generation: 24                           
  name: faros.sh                           
spec:                                
  identity:                          
    secretRef:                       
      name: faros.sh                 
      namespace: kcp-system          
  latestResourceSchemas:             
  - today.requests.access.faros.sh   
  - today.agents.edge.faros.sh       
  - today.registrations.edge.faros.sh
  permissionClaims:          
  - group: access.faros.sh   
    resource: requests                                                            
  - group: edge.faros.sh                                                          
    resource: registrations                                                       
  - group: ""                                                                     
    resource: secrets                                                                                    
  - group: ""                                                                                            
    resource: serviceaccounts                                                                            
  - group: ""                                                                                                              
    resource: configmaps                                                                                                   
  - group: workload.kcp.dev                                                                                                
    identityHash: a2f09aebf5bc96033c19aaa1dbe2c1808542ad3ffd65b68e30fcdd3ae61c35cc                                         
    resource: synctargets           
```
`APIBinding`:
```
apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  name: faros.sh
spec:
  permissionClaims:
  - group: access.faros.sh
    resource: requests
    state: Accepted
  - group: edge.faros.sh
    resource: registrations
    state: Accepted
  - group: ""
    resource: serviceaccounts
    state: Accepted
  - group: ""
    resource: secrets
    state: Accepted
  - group: ""
    resource: configmaps
    state: Accepted
  - group: workload.kcp.dev
    resource: synctargets
    identityHash: ffe94b78bc62522c08e39bf04b2b24b9f27c175fce8c3f0457e42ff5fbef3b1d
    state: Accepted
  reference:
    workspace:
      exportName: faros.sh
      path: root:compute:controllers
```

And we have 2 requests from verbose level 8:
THis one we can see singple "decorations with identity"  `Path:"/apis/edge.faros.sh/v1alpha1/namespaces/default/registrations:b833587a82b737a93c56b67771d0a987b671e64b762ac5ce6614d237d8f8bb5b`
```
] startRequest(RequestDigest{RequestInfo: &request.RequestInfo{IsResourceRequest:true, Path:"/apis/edge.faros.sh/v1alpha1/namespaces/default/registrations:b833587a82b737a93c56b67771d0a987b671e64b762ac5ce6614d237d8f8bb5b", Verb:"list", APIPrefix:"apis", APIGroup:"edge.faros.sh", APIVersion:"v1alpha1", Namespace:"default", Resource:"registrations:b833587a82b737a93c56b67771d0a987b671e64b762ac5ce6614d237d8f8bb5b", Subresource:"
", Name:"", Parts:[]string{"registrations:b833587a82b737a93c56b67771d0a987b671e64b762ac5ce6614d237d8f8bb5b"}}, User: &user.DefaultInfo{Name:"system:apiserver", UID:"2fcd6aed-1c40-4a5d-963e-0ab665c7b579", Groups:[]string{"system:masters"}, Extra:map[string][]string(nil)}}) 
```

And second one we have double: `/apis/workload.kcp.dev/v1alpha1/synctargets:ffe94b78bc62522c08e39bf04b2b24b9f27c175fce8c3f0457e42ff5fbef3b1d:ffe94b78bc62522c08e39bf04b2b24b9f27c175fce8c3f0457e42ff5fbef3b1d`
```
 startRequest(RequestDigest{RequestInfo: &request.RequestInfo{IsResourceRequest:true, Path:"/apis/workload.kcp.dev/v1alpha1/synctargets:ffe94b78bc62522c08e39bf04b2b24b9f27c175fce8c3f0457e42ff5fbef3b1d:ffe94b78bc62522c08e39bf04b2b24b9f27c175fce8c3f0457e42ff5fbef3b1d", Verb:"list", APIPrefix:"apis", APIGroup:"workload.kcp.dev", APIVersion:"v1alpha1", Namespace:"", Resource:"synctargets:ffe94b78bc62522c08e39bf04b2b24b9f27c175fce8c3f0457e42ff5fbef3b1d:ffe94b78bc62522c08e39bf04b2b24b9f27c175fce8c3f0457e42ff5fbef3b1d", Subresource:"", Name:"", Parts:[]string{"synctargets:ffe94b78bc62522c08e39bf04b2b24b9f27c175fce8c3f0457e42ff5fbef3b1d:ffe94b78bc62522c08e39bf04b2b24b9f27c175fce8c3f0457e42ff5fbef3b1d"}}, User: &user.DefaultInfo{Name:"system:apiserver", UID:"2fcd6aed-1c40-4a5d-963e-0ab665c7b579", Groups:[]string{"system:masters"}, Extra:map[string][]string(nil)}})
```
This leads to 404 being returned from storage.

Existing decorations was here for a long time:
https://github.com/kcp-dev/kcp/blob/bc50273a7a1fe2f192ccf4bb4c00120d45607e7d/pkg/server/bootstrap/identity.go#L285

And we added second decorator here:
https://github.com/kcp-dev/kcp/blob/bc50273a7a1fe2f192ccf4bb4c00120d45607e7d/pkg/virtual/framework/forwardingregistry/store.go#L279 

Fix is quite simple:
```
if !strings.Contains(comps[5],":"){
    comps[5] += ":" + id
}
```

But the fact we do this in 2 locations but not all code hits `decorateWildcardPathsWithResourceIdentities`  and some hits boths. 
I didn't yet went all-in to find out how bussiness logic is constructed so this happens, but this small fix fixed beahviour for double decorations. 

### Steps To Reproduce

See description. 

### Expected Behaviour

No double decorations 

### Additional Context

https://gist.github.com/mjudeikis/39869eed948f6ab7278c0b5b7999d6a5 

:exploding_head:
