### ISSUE TITLE
bug: server URL in the generated secret of a syncer is missing :443 port when the SyncTarget was created in previous releases 

### ISSUE THREAD

**Issue by MatousJobanek** [kcp-dev/kcp#2187]
### Describe the bug

We have a SyncTarget that was created using a command from previous versions of kcp and we need to update it to the latest version of kcp.
After running `kubectl kcp workload sync` command in the same workspace, the server URL in the generated secret doesn't contain the `:443` port:

```yaml
clusters:
- name: default-cluster
  cluster:
    certificate-authority-data: 
    server: https://kcp-stable.....openshiftapps.com
```

as a result, then synced deployments are missing values of the env vars:
```yaml
env:
  - name: KUBERNETES_SERVICE_PORT
  - name: KUBERNETES_SERVICE_PORT_HTTPS
```
which ends up in a failing deployment
```
"error": "no configuration has been provided, try setting KUBERNETES_MASTER environment variable"
```

### Steps To Reproduce

1. create a SyncTarget using command `kubectl kcp workload sync`
2. take a look at the generated secret - the port is missing there
3. deploy the syncer
4. let the syncer sync any deployment - the pods will be failing 

### Expected Behaviour

* the server URL also contains the port
* synced deployments don't result in crash-looging pods

### Additional Context

the version used: v0.9.0 (for both, the syncer image as well as kubectl kcp plugin). 
Using kcp-stable
```
$ git checkout v0.9.0
$ make install
$ kubectl kcp workload sync appstudio-internal --syncer-image ghcr.io/kcp-dev/kcp/syncer:v0.9.0 --resources=services,routes.route.openshift.io,statefulsets.apps -o kcp-stable/appstudio-internal-syncer.yaml --namespace kcp-syncer-kcp-stable
```
