### ISSUE TITLE
bug: SA can bind any APIExport (no matter what RBAC is set) through a VirtualWorkspace of an APIExport that claims APIBindings

### ISSUE THREAD

**Issue by MatousJobanek** [kcp-dev/kcp#2239]
### Describe the bug

We want to implement a controller that will automatically create APIBindings in AppStudio workspaces and that will also manage their lifecycle. To be able to do that, we need an "empty" APIExport that will claim APIBindings. Whereever the APIExport is bound, the controller will automatically create additional APIBindings for all AppStudio components. 
While testing permissions of the controller's SA in the VirtualWorkspace (that claims APIBindings) I figured out that the SA can bind literally any APIExport in the entire kcp-stable instance (no matter what RBAC is set for them).

### Steps To Reproduce

```
k ws '~'

k ws create service --enter

k create sa api-manager-sa

cat <<EOF | k apply -f -
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: api-manager
spec:
  permissionClaims:
    - group: "apis.kcp.dev"
      resource: "apibindings"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-manager-role
rules:
- apiGroups:
  - apis.kcp.dev
  resources:
  - apiexports/content
  verbs:
  - '*'
  resourceNames:
  - 'api-manager'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-manager-role
subjects:
- kind: ServiceAccount
  name: api-manager-sa
  namespace: default
EOF

YOUR_USERNAME=<your-username>

cat <<EOF | k apply -f -
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bind-apiexport
subjects:
- kind: User
  name: ${YOUR_USERNAME}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bind-apiexport
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bind-apiexport
rules:
- apiGroups:
  - apis.kcp.dev
  resources:
  - apiexports
  verbs:
  - bind
  resourceNames:
  - 'api-manager'
EOF

k ws '~'

k ws create restricted-service --enter

cat <<EOF | k apply -f -
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: restricted-service
spec:
EOF

HOME_WORKSPACE=$(k ws '~' --short)

k ws create consumer --enter

cat <<EOF | k create -f -
apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  name: api-manager
spec:
  permissionClaims:
  - group: apis.kcp.dev
    resource: apibindings
    state: Accepted
  reference:
    workspace:
      exportName: api-manager
      path: ${HOME_WORKSPACE}:service
EOF

k ws ${HOME_WORKSPACE}:service

SA_TOKEN=$(k create token api-manager-sa)

VW=$(k get apiexport api-manager -o jsonpath='{.status.virtualWorkspaces[0].url}')

cat <<EOF | k create --validate=ignore --server ${VW}/clusters/${HOME_WORKSPACE}:consumer/ --token ${SA_TOKEN} -f -
apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  name: should-fail
spec:
  reference:
    workspace:
      path: ${HOME_WORKSPACE}:restricted-service
      exportName: restricted-service
EOF
```

the result of the last command was:
```
apibinding.apis.kcp.dev/should-fail created
```

### Expected Behaviour

the last command should fail for the missing "bind" permission.
