### ISSUE TITLE
bug: ClusterWorkspaceType list returns 404

### ISSUE THREAD

**Issue by mjudeikis** [kcp-dev/kcp#2244]
### Describe the bug

I have created custom `ClusterWorkspaceType`:
```
apiVersion: tenancy.kcp.dev/v1alpha1
kind: ClusterWorkspaceType
metadata:
  name: faros
spec:
  defaultAPIBindings:
  - path: root:faros-system:controllers
    exportName: access.faros.sh
  - path: root:faros-system:controllers
    exportName: edge.faros.sh
  - path: root:faros-system:controllers
    exportName: plugins.faros.sh
  defaultChildren:
    types:
    - name: universal
      path: root
```

And instantiated custom workspace:
```
 k get workspace
NAME   TYPE    PHASE   URL
bob    faros   Ready   https://192.168.1.138:6443/clusters/root:faros:default:bob
bob1   faros   Ready   https://192.168.1.138:6443/clusters/root:faros:default:bob1
```
When traversing Workspaces (like CLI command tree) , if im in "pre-configured" types and I list child workspaces, I get empty list, but if Im inside `bob` I get 404:
```
(interface {}) <nil>
(interface {}) <nil>
(interface {}) <nil>
(interface {}) <nil>
(*errors.StatusError)(0xc0008ca780)(the server could not find the requested resource (get clusterworkspaces.tenancy.kcp.dev))
(*errors.StatusError)(0xc0008cac80)(the server could not find the requested resource (get clusterworkspaces.tenancy.kcp.dev))
(interface {}) <nil>
(interface {}) <nil>
(interface {}) <nil>
(interface {}) <nil>
```
This is without fix: https://github.com/kcp-dev/kcp/pull/2242 

### Steps To Reproduce

See description 

### Expected Behaviour

Client should return empty list for list operation, not 404.

**Comment by mjudeikis** [comment]
Not working workspace:
```
apiVersion: tenancy.kcp.dev/v1beta1
kind: Workspace
...
spec:
  type:
    name: faros
    path: root
```
Working:
```
apiVersion: tenancy.kcp.dev/v1beta1
kind: Workspace
...
spec:
  type:
    name: universal
    path: root
```
