### ISSUE TITLE
bug: unable to create APIImport: no permission to bind to export "kubernetes" when the underlying user that created the location & workload workspace are same

### ISSUE THREAD

**Issue by kasturinarra** [kcp-dev/kcp#2630]
### Describe the bug

When the underlying user that created both location and workload workspace are same i see that the same user can still not bind to export "kubernetes" which is present in the location workspace

### Steps To Reproduce

1. Install v0.10.0 kcp
2. create a location workspace called `lw1`
3. Add synctarget to the workspace
4. create workload workspace called `ww1`
5. Run `kcp bind compute lw1`
6. create deployments in `ww1` and verify that they get synced to physical cluster
7. Now try to add another resource called  'route' by running the command in lw1 workspace `kubectl kcp workload sync qecluster2 --syncer-image=v0.10.0 --resources route -o syncer-qecluster2-main.yaml1`
8. Apply the same to physical cluster by running the command KUBECONFIG=kubeconfig_411 kubectl apply -f "syncer-qecluster2-main.yaml"
9. Now switch to `ww1` and try to create `apibinding for the kubernetes APIExport` in the `lw1` workspace

### Expected Behaviour

No error should be seen and user should be able to bind to export "kubernetes" in lw1 workspace

### Additional Context

After creating below clusterrole and clusterrolebinding, i could successfully bind to APIExport "kubernetes" in the lw1 workspace in ww1 workspace.

```
[knarra@knarra root-org]$ cat /tmp/clusterrole.yaml 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:kcp:apiexport:tenancy:bind
rules:
- apiGroups: ["apis.kcp.dev"]
  resources:
  - "apiexports"
  resourceNames:
  - "kubernetes"
  verbs: ["bind"]

[knarra@knarra root-org]$ cat /tmp/clusterrolebinding.yaml 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:kcp:authenticated:apiexport:tenancy:bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kcp:apiexport:tenancy:bind
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
```
