### ISSUE TITLE
bug: When selecting resources to be synced to physical cluster user should always provide resourcename + GVR of the resource if not, i see that resource does not get synced to physical cluster

### ISSUE THREAD

**Issue by kasturinarra** [kcp-dev/kcp#2718]
### Describe the bug

When selecting resources to be synced to physical cluster user should always provide resourcename + GVR of the resources, but in routes(or any other resource) case i see that providing --resources routes would show that resources have been added when run ‘kubectl synctarget -o wide’, but if a route is created in kcp they do not get synced to physical cluster and in the status of synctarget it always shows “'SSAR check failed for gvrs: route.openshift.io/v1, Resource=routes'”

### Steps To Reproduce

1. Install kcp on OCP cluster
2. Create a workspace with name ‘lw1’ by running the command `kubectl ws create lw1`
3. Add synctarget in the workspace using the command `kubectl kcp workload sync cluster411 --syncer-image ghcr.io/kcp-dev/kcp/syncer:v0.10.0  -o syncer-cluster411-main.yaml`
4. Apply the syncer-cluster411-main.yaml by running the command `KUBECONFIG=/home/knarra/Downloads/kubeconfig_411 kubectl apply -f "syncer-cluster411-main.yaml” `
5. Verify that synctarget has been added by running the command `kubectl get synctarget -o wide`
6. Now try to sync resource called routes using the command below
```
# kubectl kcp workload sync cluster411 --syncer-image ghcr.io/kcp-dev/kcp/syncer:v0.10.0 --resources route -o syncer-cluster411-main.yaml
# KUBECONFIG=/home/knarra/Downloads/kubeconfig_411 kubectl apply -f "syncer-cluster411-main.yaml"
```
7. Verify that ‘routes’ is shown in the ‘kubectl get synctarget -o wide’ output
8. Now create another workspace called ‘ww1’ by running the command ‘kubectl create ws ww1’
9. Run the command `kubectl kcp bind compute root:users:lw:ao:rh-sso-knarrakcp:lw1`
10. Run ‘kubectl api-resources’ and verify that you can see deployments, services and ingress in the workspace
11. Change to lw1 workspace by running the command ‘kubectl ws <full_path_of_lw1_workspace>’
12. Create clusterrole and clusterrolebinding using the content here https://github.com/kcp-dev/kcp/issues/2597#issuecomment-1380862841
13. Now change back to ww1 workspace by running the command ‘kubectl ws <full_path_of_ww1_workspace>’
14. Create an api binding using the content below
```
echo "apiVersion: apis.kcp.dev/v1alpha1
> kind: APIBinding
> metadata:
>   name: kubernetes
> spec:
>   reference:
>     workspace:
>       path: root:users:lw:ao:rh-sso-knarrakcp:lw11
>       exportName: kubernetes" | kubectl create -f -
```

15. Now run the command ‘kubectl api-resources | grep routes’ to see if routes are available in the workspace
16. Now use the yaml file below to create deployment, service and route
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: basic-ocp-demo
  name: basic-ocp-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-ocp-demo
  template:
    metadata:
      labels:
        app: basic-ocp-demo
    spec:
      containers:
      - image: quay.io/freedomben/basic-ocp-demo:latest
        name: basic-ocp-demo
        imagePullPolicy: Always
        ports:
        - containerPort: 4567
          protocol: TCP
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /healthz
            port: 4567
          initialDelaySeconds: 5
          periodSeconds: 1
        env:
        - name: BASIC_OCP_DEMO_ENV
          value: master
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: basic-ocp-demo
  name: basic-ocp-demo
spec:
  ports:
  - name: 4567-tcp
    port: 4567
    protocol: TCP
    targetPort: 4567
  selector:
    deployment: basic-ocp-demo
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: basic-ocp-demo
  name: basic-ocp-demo
spec:
  port:
    targetPort: 4567-tcp
  to:
    kind: Service
    name: basic-ocp-demo
    weight: 100
  wildcardPolicy: None
  tls:
    termination: edge
```

17. Verify that route, deployment and service is created in kcp
 18. Now login to physical cluster and see if deployment, service and route has been synced.

Actual Results:
===========
I see that only deployment, service are synced and route is not synced

```
[knarra@knarra openshift-tests-private]$ oc get all -n kcp-2ad7exs1j7c8
NAME                                  READY   STATUS    RESTARTS   AGE
pod/basic-ocp-demo-6ddb9f965c-mrbdz   1/1     Running   0          31m

NAME                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/basic-ocp-demo   ClusterIP   172.30.107.120   <none>        4567/TCP   31m

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/basic-ocp-demo   1/1     1            1           31m

NAME                                        DESIRED   CURRENT   READY   AGE
replicaset.apps/basic-ocp-demo-6ddb9f965c   1         1         1       31m
```

Running “kubectl get synctarget -o yaml” shows below status

```
- lastTransitionTime: "2023-01-17T17:44:48Z"
    message: 'SSAR check failed for gvrs: route.openshift.io/v1, Resource=routes'
    reason: SyncerUnauthorized
    severity: Error
    status: "False"
    type: SyncerAuthorized
```

### Expected Behaviour

Routes should be synced succefully and no errors should be seen in the `synctarget -o yaml` output

### Additional Context

From what i understand is in Openshift both `routes` and `routes.route.openshift.io `is supported, so kcp should as well instead of having selfsubjectaccessreview (SSAR) issue
