### ISSUE TITLE
bug: unable to create APIBinding: no permission to bind to export root:my-ws:kubernetes

### ISSUE THREAD

**Issue by dilipmighty245** [kcp-dev/kcp#2949]
### Describe the bug

Trying to create a api binding and failing with this error. 
```
unable to create APIBinding: no permission to bind to export root:my-ws:kubernetes
```
Have even added cluster role and rolebinding for the same, still the issue remains the same. 

However, I just crosschecked with compute workspace, and it is working fine

### Steps To Reproduce

Using cli plugins

```
func bind(ctx context.Context, kubeconfig string, wsName string, placementName string) error {
	opts := baseOptions.Options{
		Kubeconfig: kubeconfig,
		IOStreams:  genericclioptions.NewTestIOStreamsDiscard(),
	}
	err := opts.Complete()
	if err != nil {
		return err
	}
	logicalPath := "root"
	if spaceName != "root" {
		logicalPath = "root:" + wsName
	}
	apiExports := make([]string, 0)
	apiExports = append(apiExports, fmt.Sprintf("root:%s:kubernetes", wsName))
	bindComputeOptions := bindPlugin.NewBindComputeOptions(genericclioptions.NewTestIOStreamsDiscard())
	bindComputeOptions.LocationWorkspace = logicalcluster.Name(logicalPath).Path() 
	bindComputeOptions.BindWaitTimeout = 3 * time.Second
	bindComputeOptions.Options = &opts
	bindComputeOptions.PlacementName = wsName
	bindComputeOptions.APIExports = apiExports
	return bindComputeOptions.Run(ctx)
}

```

### Expected Behaviour

To create a api binding without any permission issue,

**Comment by ncdc** [comment]
Have you created a ClusterRole like this?

https://github.com/kcp-dev/kcp/blob/220213011478c9ac1423d9748b85db303d11ad31/config/root/clusterrole-workload-apiexport-bind.yaml

And a ClusterRoleBinding that gives permission like this?

https://github.com/kcp-dev/kcp/blob/220213011478c9ac1423d9748b85db303d11ad31/config/root/clusterrolebinding-workload-apiexport-bind.yaml

**Comment by dilipmighty245** [comment]
Hi @ncdc  

Yes i did try
```
 k get clusterrole       
NAME                                 CREATED AT
system:kcp:apiexport:workload:bind   2023-04-10T15:37:03Z

 k get clusterrolebinding
NAME                                               ROLE                                             AGE
system:kcp:authenticated:apiexport:workload:bind   ClusterRole/system:kcp:apiexport:workload:bind   42s
workspace-admin                                    ClusterRole/cluster-admin                        2m31s
```

**Comment by ncdc** [comment]
Please share the yaml for your ClusterRole - thanks

**Comment by dilipmighty245** [comment]
Please find the yaml below, its almost the same one. 

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:kcp:apiexport:workload:bind
rules:
- apiGroups: ["apis.kcp.io"]
  resources:
  - "apiexports"
  resourceNames:
  - "workload.kcp.io"
  verbs: ["bind"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:kcp:authenticated:apiexport:workload:bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kcp:apiexport:workload:bind
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
```
