### ISSUE TITLE
bug: 403 forbidden when kcp is enabled with OIDC

### ISSUE THREAD

**Issue by yogesh-reddy** [kcp-dev/kcp#2952]
### Describe the bug

Started KCP with oidc creds
```
oidc: 
  issuerUrl: https://dev-xxxx.okta.com/oauth2/default
  clientId: xxxxx
  usernameClaim: preferred_username
  groupClaim: groups
```
Provided kubconfig with oidc login creds

- name: default-dev-kuard-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: kubectl
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://dev-xxxx.okta.com/oauth2/default
      - --oidc-client-id=xxxxx
      - --oidc-extra-scope=profile
      
  The request is authorized but we are getting 403 forbidden error
  
`  Error from server (Forbidden): services is forbidden: User "https://dev-xxx.okta.com/oauth2/default#user@abc.com" cannot list resource "services" in API group "" in the namespace "default": access denied`

Created Roles and Rolebindings for the same

```apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kaurd-svc-role
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list"]
```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kaurd-dev-oidc-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kaurd-svc-role
subjects:
- kind: Group
  name: user@abc.com
```

FYI: looked at this issue https://github.com/kcp-dev/kcp/pull/2319
and made sure `preferred_username` is present in claims

### Steps To Reproduce

k get svc 

### Expected Behaviour

listing the services
