### ISSUE TITLE
bug: ServiceAccount token access leak

### ISSUE THREAD

**Issue by mjudeikis** [kcp-dev/kcp#3072]
### Describe the bug

Service account tokens from `root:outer:inner` can speak with `root:outer`

### Steps To Reproduce

1. Create organization:
```
[mjudeikis@unknown2 tilt]$ k ws create outer --enter
Workspace "inner" (type root:organization) created. Waiting for it to be ready...
Workspace "inner" (type root:organization) is ready to use.
Current workspace is "root:outer" (type root:organization).
```
2. Create basic rbac:
```
[mjudeikis@unknown2 tilt]$ k create -f config/api/resources/
namespace/api created
serviceaccount/api created
secret/api-token created
clusterrolebinding.rbac.authorization.k8s.io/api created
```
3. Extract token and see if it works
```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://kcp.dev.local:6443/clusters/outer
  name: default-cluster
contexts:
- context:
    cluster: default-cluster
    namespace: api
    user: default-user
  name: default-context
current-context: default-context
kind: Config
preferences: {}
users:
- name: default-user
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImNhSTAwODZjOWhzcUVQR2FVcGxDV1FzWUNMMVF3anZpSE9aWHhJdWRReW8ifQ.eyJpc3.......
```

You should be able to read secret and stuff.

Now create child namespace:
```
k ws create inner --enter
```
Repeat the same action to create role and test with kubeconfig. It should work. 

Now where the bug comes. Use the `inner` service account token, and try taking to `inner` resources. It should work, where it should not. 

### Expected Behaviour

Not work

**Comment by mjudeikis** [comment]
```
apiVersion: v1
kind: Namespace
metadata:
  name: api
  annotations:
    bootstrap.kcp.io/create-only: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: api
  annotations:
    bootstrap.kcp.io/create-only: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-token
  namespace: api
  annotations:
    kubernetes.io/service-account.name: api
    bootstrap.kcp.io/create-only: "true"
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api
  annotations:
    bootstrap.kcp.io/create-only: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: api
  namespace: api
```
is the rbac config
