### ISSUE TITLE
bug: `APIExportEndpointSlice.status.endpoints` does not get populated for slices without partition

### ISSUE THREAD

**Issue by tobschli** [kcp-dev/kcp#3364]
### Describe the bug

Hello everybody 😊

I am currently doing a PoC for a controller that should be kcp-aware, for which I am searching guidance through the example in the `kcp-dev/controller-runtime` examples.

Getting the `restConfig` for an `APIExport` is done there through the deprecated field `APIExport.Status.VirtualWorkspaces`, referring to use `APIExportEndpointSlice.status.endpoints` instead. ([ref](https://github.com/kcp-dev/controller-runtime/blob/607a854c2cfe6d5f50ee294bcde6a54f13b7f3ea/examples/kcp/main.go#L168-L170))

I am running a very minimal kcp-setup without any partitions, and according to the [documentation](https://docs.kcp.io/kcp/v0.27/concepts/apis/exporting-apis/#endpoint-slices):

> If you wish to get a full list of virtual workspace endpoints, just omit the spec.partition field from the example above.

Trying this out, lead me to observe that this field is not set:

```bash
k get APIExportEndpointSlices example-slice -oyaml
```
```yaml
apiVersion: apis.kcp.io/v1alpha1
kind: APIExportEndpointSlice
metadata:
  annotations:
    kcp.io/cluster: root
  creationTimestamp: "2025-04-08T13:45:53Z"
  generation: 1
  name: example-slice
  resourceVersion: "478"
  uid: 1e225e3f-9e93-414a-ac6b-bf5aefb8bca3
spec:
  export:
    name: example.kcp.io
    path: root
status:
  conditions:
  - lastTransitionTime: "2025-04-08T13:45:54Z"
    status: "True"
    type: APIExportValid
  - lastTransitionTime: "2025-04-08T13:45:54Z"
    status: "True"
    type: PartitionValid
```

### Steps To Reproduce

1. Ensure you are in the `root` workspace:
```bash
k ws .
```
```
Current workspace is 'root'.
```
2. Apply a minimal example of `APIResourceSchema`, `APIExport` and `APIExportEndpointSlice`:
```bash
cat /tmp/schemas.yaml
```
```yaml
apiVersion: apis.kcp.io/v1alpha1
kind: APIResourceSchema
metadata:
  name: v220801.widgets.example.kcp.io
spec:
  group: example.kcp.io
  names:
    categories:
    - kcp
    kind: Widget
    listKind: WidgetList
    plural: widgets
    singular: widget
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: The current phase
      jsonPath: .status.phase
      name: Phase
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      description: 'NOTE: full schema omitted for brevity'
      type: object
    served: true
    storage: true
    subresources:
      status: {}
---
apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  name: example.kcp.io
spec:
  latestResourceSchemas:
  - v220801.widgets.example.kcp.io
---
kind: APIExportEndpointSlice
apiVersion: apis.kcp.io/v1alpha1
metadata:
    name: example-slice
spec:
    export:
        path: root 
        name: example.kcp.io

```
```bash
k apply -f /tmp/schemas.yaml
```
```
apiresourceschema.apis.kcp.io/v220801.widgets.example.kcp.io created
apiexport.apis.kcp.io/example.kcp.io created
apiexportendpointslice.apis.kcp.io/example-slice created
```
3. Observe that the `APIExportSlice` is getting reconciled successfully, but the `endpoints` are not set:
```bash
k get APIExportEndpointSlices example-slice -oyaml
```
```yaml
apiVersion: apis.kcp.io/v1alpha1
kind: APIExportEndpointSlice
metadata:
  annotations:
    kcp.io/cluster: root
  creationTimestamp: "2025-04-08T13:45:53Z"
  generation: 1
  name: example-slice
  resourceVersion: "478"
  uid: 1e225e3f-9e93-414a-ac6b-bf5aefb8bca3
spec:
  export:
    name: example.kcp.io
    path: root
status:
  conditions:
  - lastTransitionTime: "2025-04-08T13:45:54Z"
    status: "True"
    type: APIExportValid
  - lastTransitionTime: "2025-04-08T13:45:54Z"
    status: "True"
    type: PartitionValid
```

### Expected Behaviour

I expected some kind of URLs to be set in the `APIExportEndpointSlice` to be set, along the lines of the example in the documentation:
```yaml
kind: APIExportEndpointSlice
apiVersion: apis.kcp.io/v1alpha1
metadata:
    name: example-slice
...
status:
    endpoints:
        - url: https://host1:6443/services/apiexport/root/example.kcp.io
        - url: https://host2:6443/services/apiexport/root/example.kcp.io
...
```
