### ISSUE TITLE
feature: Implement replication API

### ISSUE THREAD

**Issue by mjudeikis** [kcp-dev/kcp#3367]
### Feature Description

Following https://docs.google.com/document/d/18Xh2-VFnH23bDiAHPP_JXm4qAG4QK6GjTKcpszPGApQ/edit?tab=t.0

Epic: https://github.com/kcp-dev/kcp/issues/3292

We need to add a replication API to the core. The goal of the API is to enable the use of replicating objects based on `resources` into the cache server. The replicated object should be backed by the replication object and identity, and be able to be served via virtual workspace using the Replication identity.

### Proposed Solution

Add an API:

```
apiVersion: cache.kcp.io/v1alpha1
kind: PublishedResource
metadata:
  name: instances
spec:
  resource: instances.corp.com
  identity:
    secret:
    namespace:
  labelSelector:
    tier: premium 
status:
  identityHash: supersecrethash
```

It would pick resources in the same workspace where the object is and replicate them into the cache server.

Once this is replicated, we would need to create a dedicated VirtualWorkspace and serve these when it is referred in the APIExport. (Separate ticket)

### Want to contribute?

- [ ] I would like to work on this issue.
