### ISSUE TITLE
feature: Extend permissions claims with references

### ISSUE THREAD

**Issue by mjudeikis** [kcp-dev/kcp#3409]
### Feature Description

Extend permissions claims with references
https://docs.google.com/document/d/1toEU8_tldfc-kIWDgKfROyPVJGhhWDrr2cU0ayRj76I/edit?tab=t.0#heading=h.24igyjbjpe3n

Related to https://github.com/kcp-dev/kcp/issues/1937

TL:DR:
instead of `all: true` user should be able to do reference:
```
    resourceSelector:
     - reference:
         resource: MangoDBInstance
         group: mangodb.amazingcor.com
        type: corev1.ObjectReference
        JSONPath: spec.configuration
```

### Proposed Solution

https://docs.google.com/document/d/1toEU8_tldfc-kIWDgKfROyPVJGhhWDrr2cU0ayRj76I/edit?tab=t.0#heading=h.24igyjbjpe3n 

### Want to contribute?

- [ ] I would like to work on this issue.
