### ISSUE TITLE
Enable the ServiceAccount Controller to create sa secret on sa creation

### ISSUE THREAD

**Issue by Roming22** [kcp-dev/kcp#535]
I have a cluster with openshift-gitops installed, which is also running KCP in a pod. I'm trying to configure ArgoCD to control the KCP. cluster, but the registration of the KCP cluster to ArgoCD is failing. The root cause is that no token is created for the service account that ArgoCD automatically creates when registering the cluster.

Here are some logs:
```
11:48:44 - RARNAUD:~/Code/appStudio/plnsrvce-48/pipelines-service [my/gitops] (S:0 M:1 U:0)
> argocd cluster add admin_kcp --name kcp --yes --loglevel debug
INFO[0000] ServiceAccount "argocd-manager" already exists in namespace "kube-system" 
INFO[0000] ClusterRole "argocd-manager-role" updated    
INFO[0000] ClusterRoleBinding "argocd-manager-role-binding" updated 
FATA[0030] Failed to wait for service account secret: timed out waiting for the condition

14:52:05 - RARNAUD:~/Code/appStudio/plnsrvce-48/pipelines-service [my/gitops] (S:0 M:1 U:0)
> oc create serviceaccount happy-thursday -n kube-system
serviceaccount/happy-thursday created

14:52:35 - RARNAUD:~/Code/appStudio/plnsrvce-48/pipelines-service [my/gitops] (S:0 M:1 U:0)
> oc get sa -n kube-system
NAME             SECRETS   AGE
argocd-manager   0         29m
happy-thursday   0         18s

14:52:40 - RARNAUD:~/Code/appStudio/plnsrvce-48/pipelines-service [my/gitops] (S:0 M:1 U:0)
> oc get secrets -n kube-system
No resources found in kube-system namespace.
```

**Comment by ncdc** [comment]
@smarterclayton @sttts have you all thought about how we want to handle SAs & tokens in workspaces?

**Comment by ncdc** [comment]
KEP to reduce secret-based service account tokens: https://github.com/kubernetes/enhancements/tree/27fc35ee605a1417efe6394451ddecfbf2dec534/keps/sig-auth/2799-reduction-of-secret-based-service-account-token

**Comment by Roming22** [comment]
I've tried to add the annotation to the secret, but still ran into the issue. I'm not very confident I've done things properly, so here's my output:
```
17:32:31 - RARNAUD:~/Code/appStudio/plnsrvce-48/pipelines-service/ckcp [my/gitops] (S:0 M:1 U:0)
> KUBECONFIG=$KUBECONFIG_KCP oc describe sa --namespace kube-system argocd-workaround
Name:                argocd-workaround
Namespace:           kube-system
Labels:              <none>
Annotations:         <none>
Image pull secrets:  <none>
Mountable secrets:   <none>
Tokens:              <none>
Events:              <none>


17:33:12 - RARNAUD:~/Code/appStudio/plnsrvce-48/pipelines-service/ckcp [my/gitops] (S:0 M:1 U:0)
> KUBECONFIG=$KUBECONFIG_KCP oc describe secret --namespace kube-system argocd-workaround
Name:         argocd-workaround
Namespace:    kube-system
Labels:       <none>
Annotations:  kubernetes.io/service-account.name: argocd-workaround

Type:  Opaque

Data
====
ca.crt:     3156 bytes
namespace:  16 bytes
token:      36 bytes


17:33:32 - RARNAUD:~/Code/appStudio/plnsrvce-48/pipelines-service/ckcp [my/gitops] (S:0 M:1 U:0)
> KUBECONFIG="$KUBECONFIG_MERGED" argocd cluster add admin_kcp --name=kcp --service-account argocd-workaround --yes
FATA[0030] Failed to wait for service account secret: timed out waiting for the condition 
```

Did I set the annotation properly? Do I need more annotations on other objects?

**Comment by ncdc** [comment]
@Roming22 do you have `type: kubernetes.io/service-account-token` in your secret?

**Comment by ncdc** [comment]
Followed up on Slack - the SA was missing a reference to the secret. It's working now.

**Comment by Roming22** [comment]
In case anyone stumble upon this and wonders what the workaround is, here's what I used:
```
    # Manually create the serviceaccount and secret on the KCP cluster for ArgoCD to use
    local argocd_yaml="$kube_dir/argocd_kcp.yaml"
    local argocd_sa="argocd-manager"
    local argocd_ns="kube-system"
    echo "---
apiVersion: v1
kind: Secret
metadata:
  name: $argocd_sa
  namespace: $argocd_ns
  annotations:
    kubernetes.io/service-account.name: $argocd_sa
type: kubernetes.io/service-account-token
data:
  ca.crt: $(cat "$KUBECONFIG_KCP" | yq ".clusters.[0].cluster.certificate-authority-data")
  namespace: $(echo "$argocd_ns" | base64)
  token: $(cat "$KUBECONFIG_KCP" | yq ".users.[0].user.token" | tr -d '\n' | base64)
---
apiVersion: v1
kind: ServiceAccount
metadata:
  clusterName: admin
  name: $argocd_sa
  namespace: $argocd_ns
secrets:
- name: $argocd_sa" > "$argocd_yaml"
    KUBECONFIG="$KUBECONFIG_KCP" oc apply -f "$argocd_yaml" >/dev/null
    rm "$argocd_yaml"
```
