### ISSUE TITLE
system:authenticated group is not added to users

### ISSUE THREAD

**Issue by kylape** [kcp-dev/kcp#570]
**Describe the bug**
system:authenticated group is not added to users.

**To Reproduce**
1. Create a role binding that applies to system:authenticated
2. Make a request with an unprivileged user that should be authorized for the role binding created in step 1

**Expected behavior**
User would be allowed to make the request

**Comment by s-urbaniak** [comment]
@kylape can you give the concrete example of the role binding? How do you concretely execute the request, i.e. how do you construct an unprivleged user?

**Comment by ncdc** [comment]
Do we need to bind system:kcp:authenticated to system:authenticated?

**Comment by s-urbaniak** [comment]
I just tested `system:authenticated` is always already present and bound to the user, hence my confusion.

**Comment by kylape** [comment]
Sorry, I admit it is very possible I am just configuring the role bindings incorrectly.  

I am trying to let any authenticated user access the discovery endpoints in my KCP instance.  I have the admin user (auth'd via the admin token) configured in my kubeconfig context as `kcp-admin` and an unprivileged user auth'd via oidc in the context `kcp`.

Here's my (lightly edited) console output:

```
$ kubectl --context kcp-admin get clusterrolebinding discovery -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  clusterName: admin
  name: discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:discovery
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated

$ kubectl --context kcp api-resources --v=6
I0225 08:48:23.807612 1241686 loader.go:372] Config loaded from file:  /home/klape/.kube/config
I0225 08:48:24.027614 1241686 round_trippers.go:454] GET https://<hostname>/api?timeout=32s 403  in 219 milliseconds
I0225 08:48:24.086285 1241686 round_trippers.go:454] GET https://<hostname>/apis?timeout=32s 403  in 47 milliseconds
I0225 08:48:24.090898 1241686 cached_discovery.go:125] skipped caching discovery info, no groups found
NAME   SHORTNAMES   APIVERSION   NAMESPACED   KIND
```

**Comment by s-urbaniak** [comment]
ok, i have a local reproducer, debugging

**Comment by s-urbaniak** [comment]
@kylape do you mind to give me the concrete URL paths behind `kcp-admin` and `kcp`

**Comment by kylape** [comment]
Both contexts use https://kcp-admin-kcp-stage.apps.kcp-internal-1.52p3.p1.openshiftapps.com/, but `kcp-admin` uses token auth (as opposed to oidc).

**Comment by s-urbaniak** [comment]
OK, i made this work successfully. You need to grant basic access to the `default` workspace which is present in the `root` cluster. To make `discovery` work you need to grant at least a very basic access (without further permissions) to authenticated users:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:discovery
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: default-access
rules:
  - apiGroups: ["tenancy.kcp.dev"]
    resources: ["workspaces/content"]
    resourceNames: ["default"]
    verbs: ["access"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: root:default-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: default-access
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
```
